version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: flowgate
    main: ./cmd/api
    binary: flowgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: mustapha-aminu-abubakar
    name: flowgate

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
