coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 60%

comment:
  layout: "header, diff, uncovered"
  behavior: default
