// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (owner_id, currency) VALUES ($1, $2) RETURNING id, owner_id, balance, currency, created_at, updated_at
`

type CreateAccountParams struct {
	OwnerID  uuid.UUID `json:"owner_id"`
	Currency Currency  `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.OwnerID, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditAccountBalance = `-- name: CreditAccountBalance :one
UPDATE accounts
SET balance = balance + $1, updated_at = now()
WHERE id = $2
RETURNING id, owner_id, balance, currency, created_at, updated_at
`

type CreditAccountBalanceParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) CreditAccountBalance(ctx context.Context, arg CreditAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, creditAccountBalance, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductAccountBalance = `-- name: DeductAccountBalance :one
UPDATE accounts
SET balance = balance - $1, updated_at = now()
WHERE id = $2 AND balance >= $1
RETURNING id, owner_id, balance, currency, created_at, updated_at
`

type DeductAccountBalanceParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) DeductAccountBalance(ctx context.Context, arg DeductAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, deductAccountBalance, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, owner_id, balance, currency, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByOwnerID = `-- name: GetAccountByOwnerID :one
SELECT id, owner_id, balance, currency, created_at, updated_at FROM accounts WHERE owner_id = $1
`

func (q *Queries) GetAccountByOwnerID(ctx context.Context, ownerID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByOwnerID, ownerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
