// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_endpoints.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO api_endpoints (provider_id, route, method, price_amount, currency, rate_limit)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at
`

type CreateEndpointParams struct {
	ProviderID  uuid.UUID      `json:"provider_id"`
	Route       string         `json:"route"`
	Method      string         `json:"method"`
	PriceAmount pgtype.Numeric `json:"price_amount"`
	Currency    Currency       `json:"currency"`
	RateLimit   pgtype.Int4    `json:"rate_limit"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ProviderID,
		arg.Route,
		arg.Method,
		arg.PriceAmount,
		arg.Currency,
		arg.RateLimit,
	)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM api_endpoints WHERE id = $1 AND provider_id = $2
`

type DeleteEndpointParams struct {
	ID         uuid.UUID `json:"id"`
	ProviderID uuid.UUID `json:"provider_id"`
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, arg.ID, arg.ProviderID)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at FROM api_endpoints WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id uuid.UUID) (ApiEndpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i ApiEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByProviderRouteMethod = `-- name: GetEndpointByProviderRouteMethod :one
SELECT
    ae.id, ae.provider_id, ae.route, ae.method, ae.price_amount, ae.currency, ae.rate_limit, ae.status, ae.created_at, ae.updated_at,
    p.owner_id AS provider_owner_id,
    p.base_url AS provider_base_url
FROM api_endpoints ae
JOIN providers p ON p.id = ae.provider_id
WHERE ae.provider_id = $1 AND ae.route = $2 AND ae.method = $3 AND ae.status = 'active'
`

type GetEndpointByProviderRouteMethodParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Route      string    `json:"route"`
	Method     string    `json:"method"`
}

type GetEndpointByProviderRouteMethodRow struct {
	ID              uuid.UUID      `json:"id"`
	ProviderID      uuid.UUID      `json:"provider_id"`
	Route           string         `json:"route"`
	Method          string         `json:"method"`
	PriceAmount     pgtype.Numeric `json:"price_amount"`
	Currency        Currency       `json:"currency"`
	RateLimit       pgtype.Int4    `json:"rate_limit"`
	Status          EndpointStatus `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ProviderOwnerID uuid.UUID      `json:"provider_owner_id"`
	ProviderBaseUrl string         `json:"provider_base_url"`
}

func (q *Queries) GetEndpointByProviderRouteMethod(ctx context.Context, arg GetEndpointByProviderRouteMethodParams) (GetEndpointByProviderRouteMethodRow, error) {
	row := q.db.QueryRow(ctx, getEndpointByProviderRouteMethod, arg.ProviderID, arg.Route, arg.Method)
	var i GetEndpointByProviderRouteMethodRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Route,
		&i.Method,
		&i.PriceAmount,
		&i.Currency,
		&i.RateLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderOwnerID,
		&i.ProviderBaseUrl,
	)
	return i, err
}

const listEndpointsByProvider = `-- name: ListEndpointsByProvider :many
SELECT id, provider_id, route, method, price_amount, currency, rate_limit, status, created_at, updated_at FROM api_endpoints WHERE provider_id = $1 ORDER BY route ASC
`

func (q *Queries) ListEndpointsByProvider(ctx context.Context, providerID uuid.UUID) ([]ApiEndpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiEndpoint
	for rows.Next() {
		var i ApiEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Route,
			&i.Method,
			&i.PriceAmount,
			&i.Currency,
			&i.RateLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :exec
UPDATE api_endpoints
SET price_amount = $3, rate_limit = $4, status = $5, updated_at = now()
WHERE id = $1 AND provider_id = $2
`

type UpdateEndpointParams struct {
	ID          uuid.UUID      `json:"id"`
	ProviderID  uuid.UUID      `json:"provider_id"`
	PriceAmount pgtype.Numeric `json:"price_amount"`
	RateLimit   pgtype.Int4    `json:"rate_limit"`
	Status      EndpointStatus `json:"status"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) error {
	_, err := q.db.Exec(ctx, updateEndpoint,
		arg.ID,
		arg.ProviderID,
		arg.PriceAmount,
		arg.RateLimit,
		arg.Status,
	)
	return err
}
