// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, label, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, key_hash, label, status, created_at, expires_at
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     pgtype.Text        `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    ak.id, ak.user_id, ak.key_hash, ak.label, ak.status, ak.created_at, ak.expires_at,
    u.id AS user_id,
    u.email AS user_email,
    u.role AS user_role
FROM api_keys ak
JOIN users u ON u.id = ak.user_id
WHERE ak.key_hash = $1 AND ak.status = 'active'
`

type GetAPIKeyByHashRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     pgtype.Text        `json:"label"`
	Status    ApiKeyStatus       `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID_2  uuid.UUID          `json:"user_id_2"`
	UserEmail string             `json:"user_email"`
	UserRole  UserRole           `json:"user_role"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID_2,
		&i.UserEmail,
		&i.UserRole,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, key_hash, label, status, created_at, expires_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.Label,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET status = 'revoked' WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}
