// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deposits.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmDeposit = `-- name: ConfirmDeposit :exec
UPDATE deposits SET status = 'confirmed', confirmed_at = now() WHERE id = $1
`

func (q *Queries) ConfirmDeposit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmDeposit, id)
	return err
}

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (account_id, from_address, amount, currency, memo, tx_hash, status)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, account_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at
`

type CreateDepositParams struct {
	AccountID   uuid.UUID      `json:"account_id"`
	FromAddress string         `json:"from_address"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    Currency       `json:"currency"`
	Memo        pgtype.Text    `json:"memo"`
	TxHash      string         `json:"tx_hash"`
	Status      DepositStatus  `json:"status"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.AccountID,
		arg.FromAddress,
		arg.Amount,
		arg.Currency,
		arg.Memo,
		arg.TxHash,
		arg.Status,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const failDeposit = `-- name: FailDeposit :exec
UPDATE deposits SET status = 'failed' WHERE id = $1
`

func (q *Queries) FailDeposit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failDeposit, id)
	return err
}

const getDepositByTxHash = `-- name: GetDepositByTxHash :one
SELECT id, account_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at FROM deposits WHERE tx_hash = $1
`

func (q *Queries) GetDepositByTxHash(ctx context.Context, txHash string) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByTxHash, txHash)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FromAddress,
		&i.Amount,
		&i.Currency,
		&i.Memo,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const listDepositsByAccount = `-- name: ListDepositsByAccount :many
SELECT id, account_id, from_address, amount, currency, memo, tx_hash, status, created_at, confirmed_at FROM deposits
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDepositsByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListDepositsByAccount(ctx context.Context, arg ListDepositsByAccountParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FromAddress,
			&i.Amount,
			&i.Currency,
			&i.Memo,
			&i.TxHash,
			&i.Status,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
