// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_entries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    account_id, entry_type, amount, balance_after,
    currency, reference_id, reference_type, status, description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at
`

type CreateLedgerEntryParams struct {
	AccountID     uuid.UUID      `json:"account_id"`
	EntryType     EntryType      `json:"entry_type"`
	Amount        pgtype.Numeric `json:"amount"`
	BalanceAfter  pgtype.Numeric `json:"balance_after"`
	Currency      Currency       `json:"currency"`
	ReferenceID   pgtype.UUID    `json:"reference_id"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	Status        LedgerStatus   `json:"status"`
	Description   pgtype.Text    `json:"description"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.AccountID,
		arg.EntryType,
		arg.Amount,
		arg.BalanceAfter,
		arg.Currency,
		arg.ReferenceID,
		arg.ReferenceType,
		arg.Status,
		arg.Description,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Currency,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getLastLedgerEntry = `-- name: GetLastLedgerEntry :one
SELECT id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastLedgerEntry(ctx context.Context, accountID uuid.UUID) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLastLedgerEntry, accountID)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Currency,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, account_id, entry_type, amount, balance_after, currency, reference_id, reference_type, status, description, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.BalanceAfter,
			&i.Currency,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
