// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKeyStatus string

const (
	ApiKeyStatusActive  ApiKeyStatus = "active"
	ApiKeyStatusRevoked ApiKeyStatus = "revoked"
	ApiKeyStatusExpired ApiKeyStatus = "expired"
)

func (e *ApiKeyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyStatus(s)
	case string:
		*e = ApiKeyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyStatus: %T", src)
	}
	return nil
}

type NullApiKeyStatus struct {
	ApiKeyStatus ApiKeyStatus `json:"api_key_status"`
	Valid        bool         `json:"valid"` // Valid is true if ApiKeyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyStatus), nil
}

type BatchStatus string

const (
	BatchStatusPending    BatchStatus = "pending"
	BatchStatusProcessing BatchStatus = "processing"
	BatchStatusCompleted  BatchStatus = "completed"
	BatchStatusFailed     BatchStatus = "failed"
)

func (e *BatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchStatus(s)
	case string:
		*e = BatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchStatus: %T", src)
	}
	return nil
}

type NullBatchStatus struct {
	BatchStatus BatchStatus `json:"batch_status"`
	Valid       bool        `json:"valid"` // Valid is true if BatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatchStatus), nil
}

type Currency string

const (
	CurrencyXLM  Currency = "XLM"
	CurrencyUSDC Currency = "USDC"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency `json:"currency"`
	Valid    bool     `json:"valid"` // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type DepositStatus string

const (
	DepositStatusPending   DepositStatus = "pending"
	DepositStatusConfirmed DepositStatus = "confirmed"
	DepositStatusFailed    DepositStatus = "failed"
)

func (e *DepositStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepositStatus(s)
	case string:
		*e = DepositStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DepositStatus: %T", src)
	}
	return nil
}

type NullDepositStatus struct {
	DepositStatus DepositStatus `json:"deposit_status"`
	Valid         bool          `json:"valid"` // Valid is true if DepositStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepositStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DepositStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepositStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepositStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepositStatus), nil
}

type EndpointStatus string

const (
	EndpointStatusActive   EndpointStatus = "active"
	EndpointStatusInactive EndpointStatus = "inactive"
)

func (e *EndpointStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndpointStatus(s)
	case string:
		*e = EndpointStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EndpointStatus: %T", src)
	}
	return nil
}

type NullEndpointStatus struct {
	EndpointStatus EndpointStatus `json:"endpoint_status"`
	Valid          bool           `json:"valid"` // Valid is true if EndpointStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndpointStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EndpointStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndpointStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndpointStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndpointStatus), nil
}

type EntryType string

const (
	EntryTypeDeposit     EntryType = "deposit"
	EntryTypeReservation EntryType = "reservation"
	EntryTypeDeduction   EntryType = "deduction"
	EntryTypeRefund      EntryType = "refund"
	EntryTypeSettlement  EntryType = "settlement"
)

func (e *EntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryType(s)
	case string:
		*e = EntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryType: %T", src)
	}
	return nil
}

type NullEntryType struct {
	EntryType EntryType `json:"entry_type"`
	Valid     bool      `json:"valid"` // Valid is true if EntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryType), nil
}

type LedgerStatus string

const (
	LedgerStatusPending   LedgerStatus = "pending"
	LedgerStatusCompleted LedgerStatus = "completed"
	LedgerStatusFailed    LedgerStatus = "failed"
	LedgerStatusCancelled LedgerStatus = "cancelled"
)

func (e *LedgerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerStatus(s)
	case string:
		*e = LedgerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerStatus: %T", src)
	}
	return nil
}

type NullLedgerStatus struct {
	LedgerStatus LedgerStatus `json:"ledger_status"`
	Valid        bool         `json:"valid"` // Valid is true if LedgerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerStatus), nil
}

type ProviderStatus string

const (
	ProviderStatusActive    ProviderStatus = "active"
	ProviderStatusInactive  ProviderStatus = "inactive"
	ProviderStatusSuspended ProviderStatus = "suspended"
)

func (e *ProviderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderStatus(s)
	case string:
		*e = ProviderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderStatus: %T", src)
	}
	return nil
}

type NullProviderStatus struct {
	ProviderStatus ProviderStatus `json:"provider_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProviderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderStatus), nil
}

type SettlementEntryStatus string

const (
	SettlementEntryStatusPending   SettlementEntryStatus = "pending"
	SettlementEntryStatusCompleted SettlementEntryStatus = "completed"
	SettlementEntryStatusFailed    SettlementEntryStatus = "failed"
)

func (e *SettlementEntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettlementEntryStatus(s)
	case string:
		*e = SettlementEntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SettlementEntryStatus: %T", src)
	}
	return nil
}

type NullSettlementEntryStatus struct {
	SettlementEntryStatus SettlementEntryStatus `json:"settlement_entry_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if SettlementEntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettlementEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SettlementEntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettlementEntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettlementEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettlementEntryStatus), nil
}

type UsageStatus string

const (
	UsageStatusPending   UsageStatus = "pending"
	UsageStatusReserved  UsageStatus = "reserved"
	UsageStatusCompleted UsageStatus = "completed"
	UsageStatusRefunded  UsageStatus = "refunded"
	UsageStatusFailed    UsageStatus = "failed"
)

func (e *UsageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsageStatus(s)
	case string:
		*e = UsageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsageStatus: %T", src)
	}
	return nil
}

type NullUsageStatus struct {
	UsageStatus UsageStatus `json:"usage_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsageStatus), nil
}

type UserRole string

const (
	UserRoleProvider UserRole = "provider"
	UserRoleConsumer UserRole = "consumer"
	UserRoleBoth     UserRole = "both"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Account struct {
	ID        uuid.UUID      `json:"id"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	Balance   pgtype.Numeric `json:"balance"`
	Currency  Currency       `json:"currency"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ApiEndpoint struct {
	ID          uuid.UUID      `json:"id"`
	ProviderID  uuid.UUID      `json:"provider_id"`
	Route       string         `json:"route"`
	Method      string         `json:"method"`
	PriceAmount pgtype.Numeric `json:"price_amount"`
	Currency    Currency       `json:"currency"`
	RateLimit   pgtype.Int4    `json:"rate_limit"`
	Status      EndpointStatus `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ApiKey struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     pgtype.Text        `json:"label"`
	Status    ApiKeyStatus       `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Deposit struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	FromAddress string             `json:"from_address"`
	Amount      pgtype.Numeric     `json:"amount"`
	Currency    Currency           `json:"currency"`
	Memo        pgtype.Text        `json:"memo"`
	TxHash      string             `json:"tx_hash"`
	Status      DepositStatus      `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

type LedgerEntry struct {
	ID            uuid.UUID      `json:"id"`
	AccountID     uuid.UUID      `json:"account_id"`
	EntryType     EntryType      `json:"entry_type"`
	Amount        pgtype.Numeric `json:"amount"`
	BalanceAfter  pgtype.Numeric `json:"balance_after"`
	Currency      Currency       `json:"currency"`
	ReferenceID   pgtype.UUID    `json:"reference_id"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	Status        LedgerStatus   `json:"status"`
	Description   pgtype.Text    `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Provider struct {
	ID        uuid.UUID      `json:"id"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	Name      string         `json:"name"`
	BaseUrl   string         `json:"base_url"`
	Status    ProviderStatus `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type SettlementBatch struct {
	ID          uuid.UUID          `json:"id"`
	Status      BatchStatus        `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Currency    Currency           `json:"currency"`
	EntryCount  int32              `json:"entry_count"`
	TxHash      pgtype.Text        `json:"tx_hash"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type SettlementEntry struct {
	ID            uuid.UUID             `json:"id"`
	BatchID       uuid.UUID             `json:"batch_id"`
	ProviderID    uuid.UUID             `json:"provider_id"`
	Amount        pgtype.Numeric        `json:"amount"`
	Currency      Currency              `json:"currency"`
	WalletAddress string                `json:"wallet_address"`
	Status        SettlementEntryStatus `json:"status"`
	CreatedAt     time.Time             `json:"created_at"`
}

type UsageEvent struct {
	ID           uuid.UUID      `json:"id"`
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
}

type User struct {
	ID                   uuid.UUID   `json:"id"`
	Email                string      `json:"email"`
	Role                 UserRole    `json:"role"`
	DepositMemo          pgtype.Text `json:"deposit_memo"`
	PayoutStellarAddress pgtype.Text `json:"payout_stellar_address"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}
