// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (owner_id, name, base_url) VALUES ($1, $2, $3) RETURNING id, owner_id, name, base_url, status, created_at, updated_at
`

type CreateProviderParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
	BaseUrl string    `json:"base_url"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider, arg.OwnerID, arg.Name, arg.BaseUrl)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1 AND owner_id = $2
`

type DeleteProviderParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) error {
	_, err := q.db.Exec(ctx, deleteProvider, arg.ID, arg.OwnerID)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT
    p.id, p.owner_id, p.name, p.base_url, p.status, p.created_at, p.updated_at,
    u.payout_stellar_address
FROM providers p
JOIN users u ON u.id = p.owner_id
WHERE p.id = $1
`

type GetProviderByIDRow struct {
	ID                   uuid.UUID      `json:"id"`
	OwnerID              uuid.UUID      `json:"owner_id"`
	Name                 string         `json:"name"`
	BaseUrl              string         `json:"base_url"`
	Status               ProviderStatus `json:"status"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	PayoutStellarAddress pgtype.Text    `json:"payout_stellar_address"`
}

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (GetProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i GetProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutStellarAddress,
	)
	return i, err
}

const listProvidersByOwner = `-- name: ListProvidersByOwner :many
SELECT id, owner_id, name, base_url, status, created_at, updated_at FROM providers WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProvidersByOwner(ctx context.Context, ownerID uuid.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE providers
SET name = $2, base_url = $3, status = $4, updated_at = now()
WHERE id = $1 AND owner_id = $5
`

type UpdateProviderParams struct {
	ID      uuid.UUID      `json:"id"`
	Name    string         `json:"name"`
	BaseUrl string         `json:"base_url"`
	Status  ProviderStatus `json:"status"`
	OwnerID uuid.UUID      `json:"owner_id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.Exec(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.Status,
		arg.OwnerID,
	)
	return err
}
