// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AggregateProviderEarnings(ctx context.Context, cutoffTime time.Time) ([]AggregateProviderEarningsRow, error)
	ConfirmDeposit(ctx context.Context, id uuid.UUID) error
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (ApiEndpoint, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateSettlementBatch(ctx context.Context, arg CreateSettlementBatchParams) (SettlementBatch, error)
	CreateSettlementEntry(ctx context.Context, arg CreateSettlementEntryParams) (SettlementEntry, error)
	CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreditAccountBalance(ctx context.Context, arg CreditAccountBalanceParams) (Account, error)
	DeductAccountBalance(ctx context.Context, arg DeductAccountBalanceParams) (Account, error)
	DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error
	DeleteProvider(ctx context.Context, arg DeleteProviderParams) error
	FailDeposit(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByOwnerID(ctx context.Context, ownerID uuid.UUID) (Account, error)
	GetConsumerUsageSummary(ctx context.Context, consumerID uuid.UUID) ([]GetConsumerUsageSummaryRow, error)
	GetDepositByTxHash(ctx context.Context, txHash string) (Deposit, error)
	GetEndpointByID(ctx context.Context, id uuid.UUID) (ApiEndpoint, error)
	GetEndpointByProviderRouteMethod(ctx context.Context, arg GetEndpointByProviderRouteMethodParams) (GetEndpointByProviderRouteMethodRow, error)
	GetLastLedgerEntry(ctx context.Context, accountID uuid.UUID) (LedgerEntry, error)
	GetProviderByID(ctx context.Context, id uuid.UUID) (GetProviderByIDRow, error)
	GetSettlementBatchByID(ctx context.Context, id uuid.UUID) (SettlementBatch, error)
	GetUsageEventByRequestID(ctx context.Context, requestID string) (UsageEvent, error)
	GetUserByDepositMemo(ctx context.Context, depositMemo pgtype.Text) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListDepositsByAccount(ctx context.Context, arg ListDepositsByAccountParams) ([]Deposit, error)
	ListEndpointsByProvider(ctx context.Context, providerID uuid.UUID) ([]ApiEndpoint, error)
	ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error)
	ListProvidersByOwner(ctx context.Context, ownerID uuid.UUID) ([]Provider, error)
	ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]SettlementBatch, error)
	ListSettlementBatchesByProvider(ctx context.Context, arg ListSettlementBatchesByProviderParams) ([]SettlementBatch, error)
	ListSettlementEntriesByBatch(ctx context.Context, batchID uuid.UUID) ([]ListSettlementEntriesByBatchRow, error)
	ListSettlementEntriesByProvider(ctx context.Context, arg ListSettlementEntriesByProviderParams) ([]SettlementEntry, error)
	ListUsageEventsByConsumer(ctx context.Context, arg ListUsageEventsByConsumerParams) ([]ListUsageEventsByConsumerRow, error)
	ListUsageEventsByProvider(ctx context.Context, arg ListUsageEventsByProviderParams) ([]ListUsageEventsByProviderRow, error)
	MarkUsageEventsAsSettled(ctx context.Context, arg MarkUsageEventsAsSettledParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SetUserDepositMemo(ctx context.Context, arg SetUserDepositMemoParams) error
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) error
	UpdateSettlementBatch(ctx context.Context, arg UpdateSettlementBatchParams) error
	UpdateSettlementEntryStatus(ctx context.Context, arg UpdateSettlementEntryStatusParams) error
	UpdateUserPayoutAddress(ctx context.Context, arg UpdateUserPayoutAddressParams) error
}

var _ Querier = (*Queries)(nil)
