// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlement_entries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlementEntry = `-- name: CreateSettlementEntry :one
INSERT INTO settlement_entries (batch_id, provider_id, amount, currency, wallet_address, status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, batch_id, provider_id, amount, currency, wallet_address, status, created_at
`

type CreateSettlementEntryParams struct {
	BatchID       uuid.UUID             `json:"batch_id"`
	ProviderID    uuid.UUID             `json:"provider_id"`
	Amount        pgtype.Numeric        `json:"amount"`
	Currency      Currency              `json:"currency"`
	WalletAddress string                `json:"wallet_address"`
	Status        SettlementEntryStatus `json:"status"`
}

func (q *Queries) CreateSettlementEntry(ctx context.Context, arg CreateSettlementEntryParams) (SettlementEntry, error) {
	row := q.db.QueryRow(ctx, createSettlementEntry,
		arg.BatchID,
		arg.ProviderID,
		arg.Amount,
		arg.Currency,
		arg.WalletAddress,
		arg.Status,
	)
	var i SettlementEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.WalletAddress,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listSettlementEntriesByBatch = `-- name: ListSettlementEntriesByBatch :many
SELECT
    se.id, se.batch_id, se.provider_id, se.amount, se.currency, se.wallet_address, se.status, se.created_at,
    p.name AS provider_name
FROM settlement_entries se
JOIN providers p ON p.id = se.provider_id
WHERE se.batch_id = $1
ORDER BY se.created_at ASC
`

type ListSettlementEntriesByBatchRow struct {
	ID            uuid.UUID             `json:"id"`
	BatchID       uuid.UUID             `json:"batch_id"`
	ProviderID    uuid.UUID             `json:"provider_id"`
	Amount        pgtype.Numeric        `json:"amount"`
	Currency      Currency              `json:"currency"`
	WalletAddress string                `json:"wallet_address"`
	Status        SettlementEntryStatus `json:"status"`
	CreatedAt     time.Time             `json:"created_at"`
	ProviderName  string                `json:"provider_name"`
}

func (q *Queries) ListSettlementEntriesByBatch(ctx context.Context, batchID uuid.UUID) ([]ListSettlementEntriesByBatchRow, error) {
	rows, err := q.db.Query(ctx, listSettlementEntriesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementEntriesByBatchRow
	for rows.Next() {
		var i ListSettlementEntriesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ProviderID,
			&i.Amount,
			&i.Currency,
			&i.WalletAddress,
			&i.Status,
			&i.CreatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementEntriesByProvider = `-- name: ListSettlementEntriesByProvider :many
SELECT id, batch_id, provider_id, amount, currency, wallet_address, status, created_at FROM settlement_entries
WHERE provider_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSettlementEntriesByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSettlementEntriesByProvider(ctx context.Context, arg ListSettlementEntriesByProviderParams) ([]SettlementEntry, error) {
	rows, err := q.db.Query(ctx, listSettlementEntriesByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementEntry
	for rows.Next() {
		var i SettlementEntry
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ProviderID,
			&i.Amount,
			&i.Currency,
			&i.WalletAddress,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlementEntryStatus = `-- name: UpdateSettlementEntryStatus :exec
UPDATE settlement_entries SET status = $2 WHERE id = $1
`

type UpdateSettlementEntryStatusParams struct {
	ID     uuid.UUID             `json:"id"`
	Status SettlementEntryStatus `json:"status"`
}

func (q *Queries) UpdateSettlementEntryStatus(ctx context.Context, arg UpdateSettlementEntryStatusParams) error {
	_, err := q.db.Exec(ctx, updateSettlementEntryStatus, arg.ID, arg.Status)
	return err
}
