// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlement_batches.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlementBatch = `-- name: CreateSettlementBatch :one
INSERT INTO settlement_batches (status, total_amount, currency, entry_count)
VALUES ($1, $2, $3, $4) RETURNING id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at
`

type CreateSettlementBatchParams struct {
	Status      BatchStatus    `json:"status"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Currency    Currency       `json:"currency"`
	EntryCount  int32          `json:"entry_count"`
}

func (q *Queries) CreateSettlementBatch(ctx context.Context, arg CreateSettlementBatchParams) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, createSettlementBatch,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.EntryCount,
	)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.EntryCount,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSettlementBatchByID = `-- name: GetSettlementBatchByID :one
SELECT id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at FROM settlement_batches WHERE id = $1
`

func (q *Queries) GetSettlementBatchByID(ctx context.Context, id uuid.UUID) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, getSettlementBatchByID, id)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.EntryCount,
		&i.TxHash,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listSettlementBatches = `-- name: ListSettlementBatches :many
SELECT id, status, total_amount, currency, entry_count, tx_hash, created_at, completed_at FROM settlement_batches
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSettlementBatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]SettlementBatch, error) {
	rows, err := q.db.Query(ctx, listSettlementBatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementBatch
	for rows.Next() {
		var i SettlementBatch
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.EntryCount,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementBatchesByProvider = `-- name: ListSettlementBatchesByProvider :many
SELECT DISTINCT sb.id, sb.status, sb.total_amount, sb.currency, sb.entry_count, sb.tx_hash, sb.created_at, sb.completed_at
FROM settlement_batches sb
JOIN settlement_entries se ON se.batch_id = sb.id
WHERE se.provider_id = $1
ORDER BY sb.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSettlementBatchesByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSettlementBatchesByProvider(ctx context.Context, arg ListSettlementBatchesByProviderParams) ([]SettlementBatch, error) {
	rows, err := q.db.Query(ctx, listSettlementBatchesByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementBatch
	for rows.Next() {
		var i SettlementBatch
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.EntryCount,
			&i.TxHash,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlementBatch = `-- name: UpdateSettlementBatch :exec
UPDATE settlement_batches
SET status = $2, tx_hash = $3, completed_at = now()
WHERE id = $1
`

type UpdateSettlementBatchParams struct {
	ID     uuid.UUID   `json:"id"`
	Status BatchStatus `json:"status"`
	TxHash pgtype.Text `json:"tx_hash"`
}

func (q *Queries) UpdateSettlementBatch(ctx context.Context, arg UpdateSettlementBatchParams) error {
	_, err := q.db.Exec(ctx, updateSettlementBatch, arg.ID, arg.Status, arg.TxHash)
	return err
}
