// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_events.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateProviderEarnings = `-- name: AggregateProviderEarnings :many
SELECT
    ue.provider_id,
    SUM(ue.request_cost)::numeric AS total_earned,
    COUNT(*)::bigint AS total_requests
FROM usage_events ue
WHERE ue.status = 'completed' AND ue.created_at < $1
GROUP BY ue.provider_id
HAVING SUM(ue.request_cost) > 0
`

type AggregateProviderEarningsRow struct {
	ProviderID    uuid.UUID      `json:"provider_id"`
	TotalEarned   pgtype.Numeric `json:"total_earned"`
	TotalRequests int64          `json:"total_requests"`
}

func (q *Queries) AggregateProviderEarnings(ctx context.Context, cutoffTime time.Time) ([]AggregateProviderEarningsRow, error) {
	rows, err := q.db.Query(ctx, aggregateProviderEarnings, cutoffTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateProviderEarningsRow
	for rows.Next() {
		var i AggregateProviderEarningsRow
		if err := rows.Scan(&i.ProviderID, &i.TotalEarned, &i.TotalRequests); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUsageEvent = `-- name: CreateUsageEvent :one
INSERT INTO usage_events (
    consumer_id, provider_id, endpoint_id, request_cost, currency,
    status_code, latency_ms, response_size, request_id, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at
`

type CreateUsageEventParams struct {
	ConsumerID   uuid.UUID      `json:"consumer_id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	EndpointID   uuid.UUID      `json:"endpoint_id"`
	RequestCost  pgtype.Numeric `json:"request_cost"`
	Currency     Currency       `json:"currency"`
	StatusCode   pgtype.Int4    `json:"status_code"`
	LatencyMs    pgtype.Int4    `json:"latency_ms"`
	ResponseSize pgtype.Int4    `json:"response_size"`
	RequestID    string         `json:"request_id"`
	Status       UsageStatus    `json:"status"`
}

func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, createUsageEvent,
		arg.ConsumerID,
		arg.ProviderID,
		arg.EndpointID,
		arg.RequestCost,
		arg.Currency,
		arg.StatusCode,
		arg.LatencyMs,
		arg.ResponseSize,
		arg.RequestID,
		arg.Status,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.ConsumerID,
		&i.ProviderID,
		&i.EndpointID,
		&i.RequestCost,
		&i.Currency,
		&i.StatusCode,
		&i.LatencyMs,
		&i.ResponseSize,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getConsumerUsageSummary = `-- name: GetConsumerUsageSummary :many
SELECT
    p.name AS provider_name,
    COUNT(*)::bigint AS total_requests,
    SUM(ue.request_cost)::numeric AS total_spent
FROM usage_events ue
JOIN providers p ON p.id = ue.provider_id
WHERE ue.consumer_id = $1
GROUP BY p.name
ORDER BY total_spent DESC
`

type GetConsumerUsageSummaryRow struct {
	ProviderName  string         `json:"provider_name"`
	TotalRequests int64          `json:"total_requests"`
	TotalSpent    pgtype.Numeric `json:"total_spent"`
}

func (q *Queries) GetConsumerUsageSummary(ctx context.Context, consumerID uuid.UUID) ([]GetConsumerUsageSummaryRow, error) {
	rows, err := q.db.Query(ctx, getConsumerUsageSummary, consumerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConsumerUsageSummaryRow
	for rows.Next() {
		var i GetConsumerUsageSummaryRow
		if err := rows.Scan(&i.ProviderName, &i.TotalRequests, &i.TotalSpent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageEventByRequestID = `-- name: GetUsageEventByRequestID :one
SELECT id, consumer_id, provider_id, endpoint_id, request_cost, currency, status_code, latency_ms, response_size, request_id, status, created_at FROM usage_events WHERE request_id = $1
`

func (q *Queries) GetUsageEventByRequestID(ctx context.Context, requestID string) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByRequestID, requestID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.ConsumerID,
		&i.ProviderID,
		&i.EndpointID,
		&i.RequestCost,
		&i.Currency,
		&i.StatusCode,
		&i.LatencyMs,
		&i.ResponseSize,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageEventsByConsumer = `-- name: ListUsageEventsByConsumer :many
SELECT
    ue.id, ue.consumer_id, ue.provider_id, ue.endpoint_id, ue.request_cost, ue.currency, ue.status_code, ue.latency_ms, ue.response_size, ue.request_id, ue.status, ue.created_at,
    p.name AS provider_name,
    ae.route AS endpoint_route
FROM usage_events ue
JOIN providers p ON p.id = ue.provider_id
JOIN api_endpoints ae ON ae.id = ue.endpoint_id
WHERE ue.consumer_id = $1
ORDER BY ue.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageEventsByConsumerParams struct {
	ConsumerID uuid.UUID `json:"consumer_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListUsageEventsByConsumerRow struct {
	ID            uuid.UUID      `json:"id"`
	ConsumerID    uuid.UUID      `json:"consumer_id"`
	ProviderID    uuid.UUID      `json:"provider_id"`
	EndpointID    uuid.UUID      `json:"endpoint_id"`
	RequestCost   pgtype.Numeric `json:"request_cost"`
	Currency      Currency       `json:"currency"`
	StatusCode    pgtype.Int4    `json:"status_code"`
	LatencyMs     pgtype.Int4    `json:"latency_ms"`
	ResponseSize  pgtype.Int4    `json:"response_size"`
	RequestID     string         `json:"request_id"`
	Status        UsageStatus    `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	ProviderName  string         `json:"provider_name"`
	EndpointRoute string         `json:"endpoint_route"`
}

func (q *Queries) ListUsageEventsByConsumer(ctx context.Context, arg ListUsageEventsByConsumerParams) ([]ListUsageEventsByConsumerRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByConsumer, arg.ConsumerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByConsumerRow
	for rows.Next() {
		var i ListUsageEventsByConsumerRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.ProviderName,
			&i.EndpointRoute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByProvider = `-- name: ListUsageEventsByProvider :many
SELECT
    ue.id, ue.consumer_id, ue.provider_id, ue.endpoint_id, ue.request_cost, ue.currency, ue.status_code, ue.latency_ms, ue.response_size, ue.request_id, ue.status, ue.created_at,
    u.email AS consumer_email
FROM usage_events ue
JOIN users u ON u.id = ue.consumer_id
WHERE ue.provider_id = $1
ORDER BY ue.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageEventsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListUsageEventsByProviderRow struct {
	ID            uuid.UUID      `json:"id"`
	ConsumerID    uuid.UUID      `json:"consumer_id"`
	ProviderID    uuid.UUID      `json:"provider_id"`
	EndpointID    uuid.UUID      `json:"endpoint_id"`
	RequestCost   pgtype.Numeric `json:"request_cost"`
	Currency      Currency       `json:"currency"`
	StatusCode    pgtype.Int4    `json:"status_code"`
	LatencyMs     pgtype.Int4    `json:"latency_ms"`
	ResponseSize  pgtype.Int4    `json:"response_size"`
	RequestID     string         `json:"request_id"`
	Status        UsageStatus    `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	ConsumerEmail string         `json:"consumer_email"`
}

func (q *Queries) ListUsageEventsByProvider(ctx context.Context, arg ListUsageEventsByProviderParams) ([]ListUsageEventsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByProviderRow
	for rows.Next() {
		var i ListUsageEventsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.ProviderID,
			&i.EndpointID,
			&i.RequestCost,
			&i.Currency,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ResponseSize,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.ConsumerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUsageEventsAsSettled = `-- name: MarkUsageEventsAsSettled :exec
UPDATE usage_events SET status = $1
WHERE id = ANY($2::uuid[])
`

type MarkUsageEventsAsSettledParams struct {
	NewStatus UsageStatus `json:"new_status"`
	Ids       []uuid.UUID `json:"ids"`
}

func (q *Queries) MarkUsageEventsAsSettled(ctx context.Context, arg MarkUsageEventsAsSettledParams) error {
	_, err := q.db.Exec(ctx, markUsageEventsAsSettled, arg.NewStatus, arg.Ids)
	return err
}
