// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, role) VALUES ($1, $2) RETURNING id, email, role, deposit_memo, payout_stellar_address, created_at, updated_at
`

type CreateUserParams struct {
	Email string   `json:"email"`
	Role  UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByDepositMemo = `-- name: GetUserByDepositMemo :one
SELECT id, email, role, deposit_memo, payout_stellar_address, created_at, updated_at FROM users WHERE deposit_memo = $1
`

func (q *Queries) GetUserByDepositMemo(ctx context.Context, depositMemo pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDepositMemo, depositMemo)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, deposit_memo, payout_stellar_address, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, deposit_memo, payout_stellar_address, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.DepositMemo,
		&i.PayoutStellarAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserDepositMemo = `-- name: SetUserDepositMemo :exec
UPDATE users SET deposit_memo = $2, updated_at = now() WHERE id = $1
`

type SetUserDepositMemoParams struct {
	ID          uuid.UUID   `json:"id"`
	DepositMemo pgtype.Text `json:"deposit_memo"`
}

func (q *Queries) SetUserDepositMemo(ctx context.Context, arg SetUserDepositMemoParams) error {
	_, err := q.db.Exec(ctx, setUserDepositMemo, arg.ID, arg.DepositMemo)
	return err
}

const updateUserPayoutAddress = `-- name: UpdateUserPayoutAddress :exec
UPDATE users SET payout_stellar_address = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPayoutAddressParams struct {
	ID                   uuid.UUID   `json:"id"`
	PayoutStellarAddress pgtype.Text `json:"payout_stellar_address"`
}

func (q *Queries) UpdateUserPayoutAddress(ctx context.Context, arg UpdateUserPayoutAddressParams) error {
	_, err := q.db.Exec(ctx, updateUserPayoutAddress, arg.ID, arg.PayoutStellarAddress)
	return err
}
